---
appSettings:
  pystol:
    controller:
      image: quay.io/pystol/pystol-operator-stable:latest
    ui:
      image: quay.io/pystol/pystol-operator-stable:latest
      # The pystol UI API is exposed in 3000 port by default
      port: 3000
      # This is the host where the Pystol API
      # is supossed to be listening the UI
      host: 0.0.0.0
      # The Flask app we will run
      app: run.py
