apiVersion: apps/v1
kind: Deployment
metadata:
  name: pystol-ui
spec:
  selector:
    matchLabels:
      name: pystol-ui
      component: pystol-ui
  replicas: 1
  template:
    metadata:
      labels:
        name: pystol-ui
        component: pystol-ui
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pystol-ui
          image: pystol/operator:latest
          ports:
            - containerPort: 3000
          command: ["npm"]
          args: ["run", "server"]
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: pystol-acc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pystol-controller
spec:
  selector:
    matchLabels:
      name: pystol-controller
      component: pystol-controller
  replicas: 1
  template:
    metadata:
      labels:
        name: pystol-controller
        component: pystol-controller
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: pystol-controller
          image: pystol/operator:latest
          imagePullPolicy: Always
          command: ["pystol"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: pystol-acc

